#---------------------------------------------------------------
#                        Informação
#---------------------------------------------------------------
# autor: Leonardo Viana Pereira
# email: leonardo.viana@armateus.com.br
# version: 0.1.0
# Descrição: Ambiente com o otrs, postgresql e grafana
# Uma proposta para um gerenciamento de incidentes
#---------------------------------------------------------------



version: '3.5'
services:
#---------------------------------------------------------------
# POSTGRESQL
#---------------------------------------------------------------
  db-otrs:
    image: postgres:9.6
    container_name: pgsql-otrs
    restart: always
    environment: 
      POSTGRES_DB: otrs
      POSTGRES_USER: otrs
      POSTGRES_PASSWORD: otrs
    volumes:
    - pgsql-otrs-volume:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - server
   
#---------------------------------------------------------------
# OTRS
#---------------------------------------------------------------
  otrs: 
    #build: otrs/.
    image: leoviana00/otrs:6.0.28
    restart: always
    container_name: otrs
    environment:
      LANGUAGE: pt_BR
      FQDN: "central.ithappens.local"
      ADMINEMAIL: "root@localhost"
      ORGANIZATION: "ITHAPPENS"
      DB_TYPE: postgres 
      DB_NAME: otrs
      DB_USER: otrs
      DB_PASSWORD: otrs
      DB_HOST: db-otrs
    volumes:
    - otrs-volume:/opt/otrs
    links:
    - db-otrs:pgsql-otrs
    depends_on:
    - db-otrs
    networks:
      default:
        aliases:
          - server

#---------------------------------------------------------------
# GRAFANA
#---------------------------------------------------------------
  grafana-otrs:
    image: grafana/grafana
    restart: unless-stopped
    user: "root"
    container_name: grafana-otrs
    environment:
        GF_INSTALL_PLUGINS: grafana-clock-panel,briangann-gauge-panel,alexanderzobnin-zabbix-app,grafana-simple-json-datasource,grafana-piechart-panel
        GF_SERVER_PROTOCOL: http
        GF_SERVER_HTTP_PORT: 3000
    depends_on:
    - db-otrs 
    volumes:
    - grafana-volume:/var/lib/grafana
    links:
    - db-otrs:pgsql-otrs
    networks:
      default:
        aliases:
          - server

#------------------------------------------------------ 
volumes:
  otrs-volume:
  pgsql-otrs-volume:
  grafana-volume:

  

