{
 "title": "Central It Happens",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "NOVOS",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as cont from ticket where ticket_state_id = 1;"
    }
   ]
  },
  {
   "title": "ABERTOS",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as cont from ticket where ticket_state_id in (1,4);"
    }
   ]
  },
  {
   "title": "LEMBRETE",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as cont from ticket where ticket_state_id in (6);"
    }
   ]
  },
  {
   "title": "AGENDAMENTOS",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select \n   title as TÍTULO,start_time as INÍCIO,end_time AS FIM \nfrom\n   calendar_appointment ca\n   where start_time >= now() ;"
    }
   ]
  },
  {
   "title": "TICKETS POR SQUAD",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "rawSql": "select \n\tcc.name as SQUAD, \n\tcount(*) as TICKETS \nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.queue_id = q.id and \n\tt.ticket_state_id = ts.id and \n\tq.name <> 'Lixo' \ngroup by \n\tcc.name\norder by \n\tTICKETS desc \nlimit 10;"
    }
   ]
  },
  {
   "title": "Central",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (1,4) and queue_id in (5);\n"
    }
   ]
  },
  {
   "title": "DevOps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (1,4) and queue_id in (6);\n"
    }
   ]
  },
  {
   "title": "SysAdmin",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (1,4) and queue_id in (7);\n"
    }
   ]
  },
  {
   "title": "DBA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (1,4) and queue_id in (8);\n"
    }
   ]
  },
  {
   "title": "SLA VENCIDO",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select \n\n\tt.tn as TICKET,\n\tt.title as TÍTULO, \n\ts.name as SLA, \n\tq.name as FILA,\n\tt.create_time as ABERTURA\n\n\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tsla s\nwhere \n\tt.queue_id = q.id and \n\tt.ticket_state_id = ts.id and\n\tt.sla_id = s.id and \n\tq.name <> 'Lixo' and \n\tts.id not in (2,3,10) and \n\tto_timestamp(t.escalation_time) < NOW() and \n  t.escalation_time > 0;"
    }
   ]
  }
 ]
}