{
 "title": "Central Pulse ~",
 "time": { "from": "now-12h", "to": "now-5s" },
 "refresh": "10s",
 "panels": [
  {
   "title": "NOVOS",
   "type": "singlestat",
   "description": "Quantidade de solicitações novas que precisam ser tratadas",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as cont from ticket where ticket_state_id = 1;"
    }
   ]
  },
  {
   "title": "ABERTOS",
   "type": "singlestat",
   "description": "Solicitações que já foram tratadas e estão em andamento",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as cont from ticket where ticket_state_id in (4);"
    }
   ]
  },
  {
   "title": "LEMBRETE",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) as cont from ticket where ticket_state_id in (6);"
    }
   ]
  },
  {
   "title": "AGENDAMENTOS",
   "type": "table",
   "description": "Mostrará os compromissos registrados no calendário",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select \n   title as TÍTULO,start_time as INÍCIO,end_time AS FIM \nfrom\n   calendar_appointment ca\n   where start_time >= now() ;"
    }
   ]
  },
  {
   "title": "TICKETS POR SQUAD",
   "type": "table",
   "description": "Solicitações em andamento por time",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "rawSql": "select \n\tcc.name as SQUAD, \n\tcount(*) as TICKETS \nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.queue_id = q.id and \n\tt.ticket_state_id = ts.id and \n\tq.name <> 'Lixo' and \n\tt.ticket_state_id in (1,4)\ngroup by \n\tcc.name\norder by \n\tTICKETS desc \nlimit 10;"
    }
   ]
  },
  {
   "title": "DevOps",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  avg(id) AS \"time\",\n  customer_id AS metric,\n  count(ticket_state_id)\nFROM ticket\nWHERE\n  ticket_state_id = 1 \n  and queue_id in (6)\nGROUP BY ticket_state_id,2\nORDER BY avg (id)\n"
    }
   ]
  },
  {
   "title": "SysAdmin",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  avg(id) AS \"time\",\n  customer_id AS metric,\n  count(ticket_state_id)\nFROM ticket\nWHERE\n  ticket_state_id = 1 \n  and queue_id in (7)\nGROUP BY ticket_state_id,2\nORDER BY avg (id)\n"
    }
   ]
  },
  {
   "title": "DBA",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  avg(id) AS \"time\",\n  customer_id AS metric,\n  count(ticket_state_id)\nFROM ticket\nWHERE\n  ticket_state_id = 1 \n  and queue_id in (8)\nGROUP BY ticket_state_id,2\nORDER BY avg (id)\n"
    }
   ]
  },
  {
   "title": "SLA VENCIDO",
   "type": "table",
   "description": "Após passar o tempo de 15 minutos sem envio de resposta de atendimento inicial, o ticket aparecerá nesse quadro.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select \n\n\tt.tn as TICKET,\n\tt.title as TÍTULO, \n\ts.name as SLA, \n\tq.name as FILA,\n\tt.create_time as ABERTURA\n\n\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tsla s\nwhere \n\tt.queue_id = q.id and \n\tt.ticket_state_id = ts.id and\n\tt.sla_id = s.id and \n\tq.name <> 'Lixo' and \n\tts.id not in (2,3,10) and \n\tto_timestamp(t.escalation_time) < NOW() and \n  t.escalation_time > 0;"
    }
   ]
  }
 ]
}