{
 "title": "Central It Happens",
 "description": "Dashboard",
 "tags": [ "otrs" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "Queue",
    "query": "\tselect name as __text, id as __value from queue"
   },
   {
    "name": "state",
    "label": "State",
    "query": "select name as __text, id as __value from ticket_state"
   },
   { "name": "ANO", "query": "2018, 2019, 2020, 2021, 2022" },
   {
    "name": "MES",
    "query": "01,02,03,04,05,06,07,08,09,10,11,12"
   }
  ]
 },
 "panels": [
  { "title": "Data / Hora", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Novos",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (1) and queue_id in ($queue)"
    }
   ]
  },
  {
   "title": "Classificados",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id = 4 and queue_id in ($queue);"
    }
   ]
  },
  {
   "title": "Fechados",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (2,3,10) and queue_id in ($queue);"
    }
   ]
  },
  {
   "title": "DevOps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (1,4) and queue_id in (5);"
    }
   ]
  },
  {
   "title": "DBA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (1,4) and queue_id in (6);"
    }
   ]
  },
  {
   "title": "SysAdmin",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (1,4) and queue_id in (7);"
    }
   ]
  },
  {
   "title": "Chamados por Atendente",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select \n  u.login, \n  count(t.id) Chamados\nfrom \n  ticket t, \n  queue q, \n  users u \nwhere \n  u.id = t.responsible_user_id and \n  q.id = t.queue_id and\n  t.ticket_state_id in (1,4,11,12,13,14) and \n  q.id in ($queue)\ngroup by u.login"
    }
   ]
  }
 ]
}