{
 "title": "Pulse Central",
 "time": { "from": "1738-08-26T15:04:15.500Z", "to": "2303-08-01T14:55:43.500Z" },
 "templating": {
  "list": [
   {
    "name": "state",
    "label": "Estado",
    "query": "select name as __text, id as __value  from ticket_state"
   },
   {
    "name": "queue",
    "label": "Fila",
    "query": "select name as __text, id  as __value from queue "
   },
   {
    "name": "squad",
    "label": "Squad",
    "query": "select name as __text, customer_id as __value  from customer_company"
   }
  ]
 },
 "panels": [
  {
   "title": "JANEIRO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-01-01' and '2020-01-31' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "FEVEREIRO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-02-01' and '2020-02-29' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "MARÇO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-03-01' and '2020-03-31' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "ABRIL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-04-01' and '2020-04-30' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "MAIO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-05-01' and '2020-05-31' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "JUNHO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-06-01' and '2020-06-30' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "JULHO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-07-01' and '2020-07-31' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "AGOSTO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-08-01' and '2020-08-31' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "SETEMBRO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-09-01' and '2020-09-30' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "OUTUBRO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-10-01' and '2020-10-31' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "NOVEMBRO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-11-01' and '2020-11-30' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "DEZEMBRO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-12-01' and '2020-12-31' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "TICKETS POR FILA",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\n  $__timeGroupAlias(t.create_time,$__interval),\n  q.name as \"Fila\",\n  count(t.id) as \"TICKETS\"\n\nfrom\n  ticket t,\n  queue q ,\n  ticket_state ts,\n  customer_company cc \n  \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n  t.queue_id = q.id and\n  q.id in ($queue) and\n  \n\tt.ticket_state_id = ts.id and\n  ts.id in ($state) and\n  \n  \n  $__timeFilter(t.create_time)\n  \ngroup by\n\n\tq.name,\n\tt.create_time\n\t\norder by \n\tcount(t.id) ASC;"
    }
   ]
  },
  {
   "title": "TICKETS POR SQUADS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 7, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcc.name as CLIENTE, \n\tcount(*) as TICKETS \nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\tt.customer_id ,\n\tcc.name ,\n\tt.create_time\norder by \n\tTICKETS desc \n"
    }
   ]
  },
  {
   "title": "Tickets - Total",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-01-01' and '2020-12-31' and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\norder by \n\tJULHO desc \n"
    }
   ]
  },
  {
   "title": "TICKETS POR RESPONSÁVEL",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select \n  u.login, \n  count(t.id) \"TICKETS\"\nfrom \n  ticket t, \n  queue q, \n  users u, \n  customer_company cc \n  \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n  u.id = t.responsible_user_id and \n  q.id = t.queue_id and\n  q.id in ($queue) and\n  \n  t.ticket_state_id in ($state) \ngroup by u.login"
    }
   ]
  },
  {
   "title": "TOP 10 - SERVIÇOS",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 13 },
   "targets": [
    {
     "rawSql": "select\n\tsv.name as \"SERVIÇO\", \n\tcount(t.id) as \"TICKETS\"\nfrom\n\tticket t,\n\tqueue q,\n\tticket_state ts,\n\tservice sv,\n  customer_company cc \n  \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\tt.service_id = sv.id and\n\tt.queue_id = q.id and\n\tt.ticket_state_id = ts.id and\n\tq.id in ($queue) and\n\tts.id in ($state)\ngroup by\n\tsv.name\norder by \n\tcount(t.id) desc \nlimit 10;\n"
    }
   ]
  }
 ]
}