{
 "title": "Pulse Central",
 "time": { "from": "1456-03-09T15:08:31.500Z", "to": "2586-01-16T14:51:27.500Z" },
 "templating": {
  "list": [
   {
    "name": "state",
    "label": "Estado",
    "query": "select name as __text, id as __value  from ticket_state"
   },
   {
    "name": "queue",
    "label": "Fila",
    "query": "select name as __text, id  as __value from queue "
   },
   {
    "name": "squad",
    "label": "Squad",
    "query": "select name as __text, customer_id as __value  from customer_company"
   },
   {
    "name": "MES",
    "label": "Mês",
    "query": "01,02,03,04,05,06,07,08,09,10,11,12"
   }
  ]
 },
 "panels": [
  {
   "title": "TICKETS POR FILA",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\n  $__timeGroupAlias(t.create_time,$__interval),\n  q.name as \"Fila\",\n  count(t.id) as \"TICKETS\"\n\nfrom\n  ticket t,\n  queue q ,\n  ticket_state ts,\n  customer_company cc \n  \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n  t.queue_id = q.id and\n  q.id in ($queue) and\n  \n\tt.ticket_state_id = ts.id and\n  ts.id in ($state) and\n  date_part('month', t.create_time) IN ($MES) and\n  \n  \n  $__timeFilter(t.create_time)\n  \ngroup by\n\n\tq.name,\n\tt.create_time\n\t\norder by \n\tcount(t.id) ASC;"
    }
   ]
  },
  {
   "title": "TICKETS POR SQUADS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcc.name as CLIENTE, \n\tcount(*) as TICKETS \nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tdate_part('month', t.create_time) IN ($MES) and\n\t\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\tt.customer_id ,\n\tcc.name ,\n\tt.create_time\norder by \n\tTICKETS desc \n"
    }
   ]
  },
  {
   "title": "Tickets - Total",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select \n  $__timeGroupAlias(t.create_time,$__interval),\n\tcount(*) as JULHO\nfrom \n\tticket t, \n\tqueue q, \n\tticket_state ts, \n\tcustomer_company cc \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n\tt.queue_id = q.id and\n\tq.id in ($queue) and\n\t\n\tt.ticket_state_id = ts.id and \n\tts.id in ($state) and\n\t\n\tt.create_time BETWEEN '2020-01-01' and '2020-12-31' and\n\t\n\tdate_part('month', t.create_time) IN ($MES) and\n\t\n\t$__timeFilter(t.create_time)\ngroup by \n\t\n\tt.create_time\n\n"
    }
   ]
  },
  {
   "title": "TICKETS POR RESPONSÁVEL",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select \n  u.login, \n  count(t.id) \"TICKETS\"\nfrom \n  ticket t, \n  queue q, \n  users u, \n  customer_company cc \n  \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n  u.id = t.responsible_user_id and \n  q.id = t.queue_id and\n  q.id in ($queue) and\n  \n  date_part('month', t.create_time) IN ($MES) and\n  \n  t.ticket_state_id in ($state) \ngroup by u.login"
    }
   ]
  },
  {
   "title": "Mês",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 9, "x": 7, "y": 11 },
   "targets": [
    {
     "rawSql": " SELECT\n    $__timeGroupAlias(t.create_time,$__interval),\n    case date_part('month', t.create_time) \n        when 1 then 'Janeiro'\n        when 2 then 'Fevereiro'\n        when 3 then 'Março'\n        when 4 then 'Abril'\n        when 5 then 'Maio'\n        when 6 then 'Junho'\n        when 7 then 'Julho'\n        when 8 then 'Agosto'\n        when 9 then 'Setembro'\n        when 10 then 'Outubro'\n        when 11 then 'Novembro'\n        when 12 then 'Dezembro'\n        else 'Indefinido'\n    end AS \"Meses\",\n    count(date_part('month', t.create_time)) as value\n from\n  ticket t,\n  queue q ,\n  ticket_state ts,\n  customer_company cc \n  \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\t\n  t.queue_id = q.id and\n  q.id in ($queue) and\n  \n\tt.ticket_state_id = ts.id and\n  ts.id in ($state) and\n  \n  date_part('month', t.create_time) IN ($MES) and\n  \n  \n  $__timeFilter(t.create_time)\n  \n GROUP BY\n t.create_time,\n date_part('month', t.create_time)\n \n ORDER BY  date_part('month', t.create_time) "
    }
   ]
  },
  {
   "title": "TOP 10 - SERVIÇOS",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "rawSql": "select\n\tsv.name as \"SERVIÇO\", \n\tcount(t.id) as \"TICKETS\"\nfrom\n\tticket t,\n\tqueue q,\n\tticket_state ts,\n\tservice sv,\n  customer_company cc \n  \nwhere \n\tcc.customer_id = t.customer_id and \n\tt.customer_id in ($squad) and\n\tt.service_id = sv.id and\n\tt.queue_id = q.id and\n\tt.ticket_state_id = ts.id and\n\tq.id in ($queue) and\n\tdate_part('month', t.create_time) IN ($MES) and\n\tts.id in ($state)\ngroup by\n\tsv.name\norder by \n\tcount(t.id) desc \nlimit 10;\n"
    }
   ]
  }
 ]
}