version: '3.5'

services:
  grafana:
    image: grafana/grafana:master
    user: "root"
    container_name: grafana
    ports:
     - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,briangann-gauge-panel,alexanderzobnin-zabbix-app,grafana-simple-json-datasource,grafana-piechart-panel
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      depends_on:
      - db-otrs 
      volumes:
      - ./grafana-volume:/var/lib/grafana
      links:
      - db-otrs:pgsql-otrs
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

  volumes:
    grafana-volume: