FROM docker.io/postgres:latest

MAINTAINER Leonardo Viana <leonardo.viana@armateus.com.br>

ENV POSTGRES_PASSWORD=otrs
ENV POSTGRES_DB=otrs
ENV POSTGRES_USER=otrs


VOLUME [ "/var/lib/postgresql/data" ]


EXPOSE 5432

